openapi: 3.0.3
info:
  title: Carrier Ethernet Schema - Test API
  version: 1.0.0
  description: Simple OAS Test API that can be used to test the Carrier Ethernet schema validity with OpenAPI Generator tool as well as to generate markdown documentation and plantuml diagrams
paths:
  '/carrierEthernetEnni':
    get:
      operationId: carrierEthernetEnni
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '../carrierEthernetEnni.yaml'
  '/carrierEthernetOperatorUni':
    get:
      operationId: carrierEthernetOperatorUni
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '../carrierEthernetOperatorUni.yaml'
  '/carrierEthernetSubscriberUni':
    get:
      operationId: carrierEthernetSubscriberUni
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '../carrierEthernetSubscriberUni.yaml'
  '/carrierEthernetVirtualUni':
    get:
      operationId: carrierEthernetVirtualUni
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '../carrierEthernetVirtualUni.yaml'
  '/carrierEthernetEvc':
    get:
      operationId: carrierEthernetEvc
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '../carrierEthernetEvc.yaml'
  '/carrierEthernetOvc':
    get:
      operationId: carrierEthernetOvc
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '../carrierEthernetOvc.yaml'
  '/carrierEthernetSls':
    get:
      operationId: carrierEthernetSls
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '../carrierEthernetSls.yaml'